### ISSUE TITLE
Mac issue 

### ISSUE THREAD

**Issue by ABSynack** [NotSoSecure/android_application_analyzer#10]
tried run pip3 install -r requirements.tx 

still the through error below 

Collecting PyQt5
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Library/Python/3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Python/3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Python/3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/0n/5zrnh66j2ddfbkxymjmx_12w0000gn/T/pip-build-env-z3o3wlp3/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/0n/5zrnh66j2ddfbkxymjmx_12w0000gn/T/pip-build-env-z3o3wlp3/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/0n/5zrnh66j2ddfbkxymjmx_12w0000gn/T/pip-build-env-z3o3wlp3/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/0n/5zrnh66j2ddfbkxymjmx_12w0000gn/T/pip-build-env-z3o3wlp3/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/0n/5zrnh66j2ddfbkxymjmx_12w0000gn/T/pip-build-env-z3o3wlp3/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/0n/5zrnh66j2ddfbkxymjmx_12w0000gn/T/pip-build-env-z3o3wlp3/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ABSynack** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by sanjay-nss** [comment]
I am working on this!

Will provide update soon.

**Comment by ABSynack** [comment]
Hi Sanjay ,still same issue . .. any luck with fix

**Comment by Alexdexc** [comment]
Same issue with M1, there is a workaround for this? thank you for all the work
